#!/bin/bash
set -eu

# TODO : set providers

exec ./op-node \
    --l1=${L1_RPC_URL} \
    --l1.rpckind=any \
    --l1.beacon=${L1_BEACON_URL} \
    --l2=http://geth:8551 \
    --l2.jwt-secret=/data/jwt.txt \
    --sequencer.enabled \
    --sequencer.l1-confs=5 \
    --verifier.l1-confs=4 \
    --rollup.config=./config/${NETWORK_TYPE}/rollup.json \
    --rpc.addr=0.0.0.0 \
    --rpc.port=8547 \
    --rpc.enable-admin \
    --p2p.sequencer.key=${SEQUENCER_PRIVATE_KEY}
