#!/bin/bash
set -eu

# Check environment variables
reqenv() {
    if [ -z "${!1:-}" ]; then
        echo "Error: environment variable '$1' is not set. check .env file!"
        exit 1
    fi
}
reqenv "CONFIG_DIR"
reqenv "L1_RPC_URL"
reqenv "L1_BEACON_URL"
reqenv "L1_CHAIN_ID"
reqenv "L2_CHAIN_ID"
reqenv "FAUCET_PRIVATE_KEY"
reqenv "FAUCET_ADDRESS"

SEQUENCER_MODE=${SEQUENCER_MODE:-false}
ADDITIONAL_ARGS=""

# Initialize geth if necessary
exec ./geth init --datadir=/data ./config/genesis.json

if [ "$SEQUENCER_MODE" != "true" ]; then
    if [ "${SEQUENCER_HTTP+x}" = x ]; then
        ADDITIONAL_ARGS="$ADDITIONAL_ARGS --rollup.halt=major --rollup.sequencer-http=$SEQUENCER_HTTP"
    fi
    if [ "${BOOTNODES+x}" = x ]; then
        ADDITIONAL_ARGS="$ADDITIONAL_ARGS --bootnodes=$BOOTNODES"
    fi
fi

# Run geth with specified parameters
exec ./geth \
    --datadir=/data \
    --networkid=${NETWORK_ID} \
    --syncmode=full \
    --gcmode=archive \
    --nodiscover \
    --maxpeers=0 \
    --http \
    --http.vhosts="*" \
    --http.corsdomain="*" \
    --http.addr=0.0.0.0 \
    --http.api=web3,debug,eth,txpool,net,engine \
    --ws \
    --ws.addr=0.0.0.0 \
    --ws.port=8546 \
    --ws.origins="*" \
    --ws.api=debug,eth,txpool,net,engine \
    --authrpc.vhosts="*" \
    --authrpc.addr=0.0.0.0 \
    --authrpc.port=8551 \
    --authrpc.jwtsecret=/data/jwt.txt \
    --rollup.disabletxpoolgossip=true \
    $ADDITIONAL_ARGS